# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/movie_recommendation
spring.datasource.username=root
spring.datasource.password=Venky2005

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Server
server.port=8080
